feat: services
maurisilvera/Calculator pull request #3
Opened 2023-04-26 15:32 UTC by maurisilvera

## Summary

Crear los siguientes servicios para cubrir los siguientes métodos:
- **GET**: la respuesta esperada es que devuelva las notas/expresiones.
- **POST**: Va a recibir las notas/expresiones y devolver un mensaje.
- **PUT**: Va a recibir una nota/expresión y va a devolver un mensaje.
- **DELETE**: Va a recibir una nota/expresión y va a devolver un mensaje.

Cuando guardemos una nota/expresión vamos a usar el servicio que creamos y el método POST para poder guardar nuestra nota/expresión en nuestra API, mostrar mensaje que devuelve el servicio al usuario.

Las notas/expresiones que se ven en la sección historial deben ser recuperadas del servicio que creamos con el metodo GET.

Cuando editemos una nota/expresión vamos a usar el servicio que creamos y el método PUT para poder guardar nuestra nota/expresión editada en nuestra API, mostrar mensaje que devuelve el servicio al usuario.

Cuando borremos una o varias notas/expresiones vamos a usar el servicio que creamos y el método DELETE para poder borrar estas en nuestra API, mostrar mensaje que devuelve el servicio al usuario.

## Test Cases

- Realizar una operacion dentro de la calculadora, y al darle = o en su defecto Enter, debera aparecer un mensaje recibido por la API confirmando que dicho resultado se guardo en el historial.
- Dentro del sitio del historial, revisar que cargue por defecto los 2 valores recibidos por la API: 123 y 654.
- Dentro del sitio del historial, modificar uno de los valores, debera aparecer un mensaje confirmando que la edicion fue exitosa.
- Dentro del sitio del historial, eliminar uno de los valores, debera aparecer un mensaje confirmando que la eliminacion fue exitosa.

## Screenshots

### Agregar resultado

![image](https://user-images.githubusercontent.com/129180621/234600894-75272ea6-0d03-4d77-85e3-4ee2c8c9950c.png)

### Editar resultado

![image](https://user-images.githubusercontent.com/129180621/234601114-689c19cb-c447-4962-b7cc-b3b5d41cb682.png)

### Eliminar resultado

![image](https://user-images.githubusercontent.com/129180621/234601224-9cdebd9a-d0f9-4cd7-a3b6-0bcc087c7bbe.png)

## Jira Card

[Card](https://trello.com/c/B1RfBFAz/29-agregando-servicios-a-la-app)

2023-04-26 18:39 UTC, facu-rodriguez requested changes
Muy buen trabajo Mau, ya casi estamos! Checkeate estos cambios y escribime!

2023-04-26 18:39 UTC, facu-rodriguez commented on src/app/screens/History/index.js
> +    dispatch(actionCreators.deleteExpressions());
lo mismo que arriba

2023-04-26 18:39 UTC, facu-rodriguez commented on src/app/components/Calculator/index.js
> +      dispatch(actionCreators.postExpressions({ id: uuidv4(), value: math.evaluate(exp) }));
Se te ocurre alguna otra manera de manejar esto? Si querés nos juntamos y lo vemos

2023-04-26 18:39 UTC, facu-rodriguez commented on src/app/screens/History/index.js
> +    dispatch(actionCreators.putExpressions());
lo mismo que arriba

2023-04-26 18:39 UTC, facu-rodriguez commented on src/redux/history/reducer.js
> +  }
```suggestion
  serviceMessages: ''
  ```

2023-04-26 19:32 UTC, maurisilvera commented on src/redux/history/reducer.js
> +  }
Al final elimine este campo ya que no se estaba utilizando para los servicios.

2023-04-26 19:32 UTC, maurisilvera commented on src/app/screens/History/index.js
> +    dispatch(actionCreators.putExpressions());
corregido!

2023-04-26 19:33 UTC, maurisilvera commented on src/app/components/Calculator/index.js
> +      dispatch(actionCreators.postExpressions({ id: uuidv4(), value: math.evaluate(exp) }));
corregido!

2023-04-26 19:33 UTC, maurisilvera commented on src/app/screens/History/index.js
> +    dispatch(actionCreators.deleteExpressions());
corregido!

2023-04-27 17:29 UTC, facu-rodriguez requested changes
Perfecto Mau! Unas cosas chiquitas nomas

si toco el igual sin haber ingresado valores crashea:
![Captura de pantalla de 2023-04-27 14-24-30](https://user-images.githubusercontent.com/68086087/234941358-992b487c-173b-4a7f-a591-e72aa5bce76c.png)

a demás, se está guardando la expresión aunque esté vacía, hacete una validación para checkear que no sea vacía la expresión antes de hacer el post

2023-04-27 17:56 UTC, maurisilvera commented
@facu-rodriguez solucionado!

2023-04-27 19:12 UTC, facu-rodriguez requested changes
se que es muy rompebolas, pero te vas a entretener un rato. Si hago click en el input y meto un espacio con la barra espaciadora y toco el igual, crashea: 
![Captura de pantalla de 2023-04-27 16-12-06](https://user-images.githubusercontent.com/68086087/234967719-c7a1d590-4815-46d1-992e-a9c7cfcafdbc.png)

2023-04-28 13:49 UTC, maurisilvera commented
@facu-rodriguez Resuelto! Me di cuenta que esto era algo que estaba en la rama calculator. Podremos si ya esta todo ok ver como mergear las 3 ramas en conjunto? Gracias!

2023-05-03 13:16 UTC, facu-rodriguez approved these changes

2023-05-09 13:18 UTC, closed without merging